### PR TITLE
Basic Reactivity

### PR DESCRIPTION
**Pull request by wfischer42**
This PR adds reactivity to the vue-cytoscape, specifically for the `data` and `position` element attributes. It also includes minor adjustments to the example config & data, adding types and exporting them separately. 

It also includes a change that should add flexibility to how ID's are added, though I haven't fully tested it.

I'm working on adding an `animate: boolean` prop for elements that will add an animation to a reactive position change, and I'll finish adding reactivity to the remaining cytoscape element attributes, such as `classes`, `renderedPosition`, `selected`, and so on. I'm doing them manually to avoid the "remove and re-add" approach to updates, which doesn't work particularly well if you're dealing with nodes with connected edges.

### CODE REVIEW

**Comment by wfischer42** [comment]
Addresses issues #41, #20, and #32

**Comment by wfischer42** [comment]
Yeah, no problem!  I'll take care of it now.
I'm new to contributing to open-source, so thanks for the review.

Also, I've never used Vuepress -- would you like me to figure it out and add documentation for the changes?

**Comment by rcarcasses** [comment]
thank you again. For adding/editing documentation modify the `.md` files here:

https://github.com/rcarcasses/vue-cytoscape/tree/master/docs

once committed, documentation will be build automatically.

**Comment by wfischer42** [comment]
Documentation is updated! I didn't provide examples, but I did originally make changes to `App.vue` to 'test' and demonstrate reactivity (not sure if that will affect the codepen). Is that good enough for now?

**Comment by rcarcasses** [comment]
Sounds fantastic! Just a comment: perhaps in the future it is convenient to rewrite the logic using [proxy objects' api](https://www.vuemastery.com/courses/advanced-components/evan-you-on-proxies/) as in the upcoming version 3 of `vue`. I have this in plan but I haven't found a slot in time to do it. Anyway your work is more than appreciated, thanks once more!

**Comment by rcarcasses** [comment]
package and documentation updated, you can double check it now! :)

**Comment by wfischer42** [comment]
I'm not sure how proxy objects work, but I'll look into it at some point and see if I can figure it out. The changes I made so far are just the ones I need for my project at the moment (and I'll add more stuff as new requirements emerge).

Also, I just noticed that I hadn't included the 1.0.7 changelog update in the root-level readme. Just wanted to point it out.

**Pull request merged**
